version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
    env_file:
      - C:\progs_arthurpereti\Docker\5_Compose\2_Variaveis\config\db.env
    ports:
      - 3308:3306
    networks: 
      - backend
  wordpress:
    image: wordpress:latest
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html
    env_file:
      - C:\progs_arthurpereti\Docker\5_Compose\2_Variaveis\config\wp.env
    ports:
      - 80:80
    networks:
      - backend

volumes:
  db_data: {}

networks:
  backend:
    driver: bridge
  